---
apiVersion: v1
kind: Pod
metadata:
  name: toolkit
  labels:
    name: toolkit
spec:
  containers:
  - args:
    - /bin/bash
    name: toolkit
    image: wasfree/toolkit:latest
    tty: true
    resources:
      limits:
        memory: "256M"
        cpu: "500m"
