name: build-push

on:
  push:
    branches:
      - master
    paths:
    - 'Dockerfile'
    - '.github/workflows/**'
  create:
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Get git tag
        id: get-tag
        run: echo "::set-output name=tag::${GITHUB_REF##*/}"
        shell: bash
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
        if: startsWith(steps.get-tag.outputs.tag, 'v')
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64,linux/ppc64le,linux/s390x
          push: true
          tags: |
            wasfree/toolkit:latest
            wasfree/toolkit:${{ steps.get-tag.outputs.tag }}
        if: startsWith(steps.get-tag.outputs.tag, 'v')